<footer class='footer col span_12_of_12 section'>
	<div class='page-wrapper'>
		<div class='link-section col span_9_of_12'>
			<div class='link-box col span_3_of_12'>
				<h4 class='h4'>About</h5>
				<ul class='links-list'>
					<li><a href='./about-us'>IITGN Alumni</a></li>
					<li><a href='http://www.iitgn.ac.in/faqs.htm' target='_blank'>IIT Gandhinagar</a></li>
					<li><a href='./about-us/executive-commitee'>Executive Committee</a></li>
					<li><a href='./about-us/coordinators'>Coordinators</a></li>
				</ul>
			</div>
			<div class='link-box col span_3_of_12'>
				<h4 class='h4'>Navigate</h5>
				<ul class='links-list'>
					<li><a href='./about-us/benefits'>Benefits</a></li>
					<li><a href='./donate'>Donate</a></li>
					<li><a href='./news-and-links'>News & links</a></li>
					<li><a href='./networks'>Networks</a></li>
					<li><a href='./contact-us'>Contact us</a></li>
				</ul>
			</div>
			<div class='link-box col span_3_of_12'>
				<h4 class='h4'>Alumni Service</h5>
				<ul class='links-list'>
					<li><a href='./networks/sign-in'>Sign In</a></li>
					<li><a href='./networks/join-alumni'>Join alumni</a></li>
					<li><a href='#'>Search directory</a></li>
					<li><a href='#'>Request transcript</a></li>
				</ul>
			</div>
			<div class='link-box col span_3_of_12'>
				<h4 class='h4'>Join us @:</h5>
				<ul class='links-list'>
					<li><a href='https://www.facebook.com/pages/IIT-Gandhinagar-Alumni-Association/264577530308384' target='_blank'>Facebook</a></li>
					<li><a href='https://twitter.com/IITGn_Alumni' target='_blank'>Twitter</a></li>
				</ul>
			</div>
		</div>
		<div class='footer-logo col span_3_of_12'>
			<a href="./" class='iitgnaa-logo'></a>
			&copy; 2013 IIT Gandhinagar
		</div>

	</div>
</footer>