<header class='header col span_12_of_12 section'>
	<div class='page-wrapper'>
		<div class='col span_3_of_12' style='height:75px;margin-top:25px'>
			<a href="<?php echo $docRoot;?>" class='iitgnaa-logo'></a>
		</div>
		<ul class='social-media col span_4_of_12'>
			<li class='media-item'>
			<a href="https://twitter.com/IITGn_Alumni" target='_blank' title='twitter' class='twitter'></a>		
			</li>
			<li class='media-item'>
			<a href="https://www.facebook.com/pages/IIT-Gandhinagar-Alumni-Association/264577530308384" target="_blank" title='facebook' class='facebook'></a>
			</li>
			<li>Join us @:</li>
		</ul>
	</div>
	<nav class='navigation-menu span_12_of_12 section'>
		<div class='page-wrapper'>
			<ul class='menu-list col span_12_of_12'>
				<li class='menu-item col span_2_of_12'><i class='fa fa-home fa-lg'></i><a href="<?php echo $docRoot;?>">Home</a></li>
				<li class='menu-item col span_2_of_12'><i class='fa fa-users'></i><a href="<?php echo $docRoot;?>about-us">About us</a></li>
				<li class='menu-item col span_2_of_12'><i class='fa fa-money'></i><a href="http://www.iitgn.org/donate">Donate</a></li>
				<li class='menu-item col span_2_of_12'><i class='fa fa-bookmark-o'></i><a href="#">News & links</a></li>
				<li class='menu-item col span_2_of_12'><i class='fa fa-sitemap'></i><a href="<?php echo $docRoot;?>networks">Networks</a></li>
				<li class='menu-item col span_2_of_12'><i class='fa fa-phone'></i><a href="<?php echo $docRoot;?>contact-us">Contact us</a></li>
			</ul>
		</div>
	</nav>
</header>